import Navbar from "./Navbar"
import Footer from "./Footer"
import Head from 'next/head'
import Login from "../src/components/login/login"




export default function Layout(){
    return(
        <>
          <Head>
        <title>Clinic Finder </title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
        <link rel="preconnect" href="https://fonts.googleapis.com"/>
        <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin/>
        <link href="https://fonts.googleapis.com/css2?family=Montserrat:wght@200&display=swap" rel="stylesheet"/>
      </Head>

        <Navbar />
        <main>
            <Login/> 
            
        </main>
        <Footer />
        
        </>

    )
}